### ISSUE TITLE
Support new Solis API v2 for S6 inverters

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/SolisAgileManager#119]
Add detection and support for the new v2.0 Solis inverter API (forked from #107).

[SolisCloud.Device.Control.API.V2.0.new.pdf](https://github.com/user-attachments/files/18921370/SolisCloud.Device.Control.API.V2.0.new.pdf)

Some useful info here: https://github.com/stevegal/solis_control/issues/32

**Comment by Webreaper** [comment]
@martinpike69 - could you send me a screenshot of the inverter control screen where you set up the charge slots please?

**Comment by martinpike69** [comment]
Yes, my old S5 (I think) / 6kw inverter used to charge and discharge at 6kw for 15 minutes (to the second), and then de-rate to 3.6kw.  Which, as far as I'm concerned, is a 3.6kw inverter that bursts to 6kw for 15 minutes, not a 6kw inverter.

Seeing as I have 9kw'ish of solar panels, and 9 x 2.4kw Pylontech US2000C batteries, the inverter was a constant bottleneck.

Fortunately, my installer was superb about it, and was annoyed as I was that his design - which was perfectly well balanced based on the spec sheet (which didn't mention the de-rating at all) - wasn't performing as it should.

They therefore - rather reluctantly - replaced the device at no cost to me.

Re charging and discharging, it has 6 slots.  I've attached screenshots of slots 1 and 2...

![Image](https://github.com/user-attachments/assets/994550ac-723d-41ba-9493-06e77886fd69)

**Comment by Webreaper** [comment]
Weird, we have the same S5 6kw, and it happily sustains 6kw,and sometimes 7-8kw for quite some time.

**Comment by martinpike69** [comment]
I'm assuming that for charging it's the target / when to stop, and for discharging it's the minimum...?

**Comment by martinpike69** [comment]
I only use 100% SOC for Charging, and 10% SOC for discharging (even though my US2000C's are meant to operate down to 5%).

**Comment by Webreaper** [comment]
More research: 
* Info here on how to check the firmware version: https://github.com/hultenvp/solis-sensor/blob/master/custom_components/solis/soliscloud_api.py#L447

**Comment by Webreaper** [comment]
If you get 5 mins, Martin, can you check your firmware version, following these steps?

https://usservice.solisinverters.com/support/solutions/articles/73000558553-how-to-determine-the-firmware-version-of-your-solis-inverter

**Comment by Webreaper** [comment]
Another reference - looks better. https://github.com/hultenvp/solis-sensor

**Comment by martinpike69** [comment]
I'm working in the garden today, but I'm more than happy to take a break from that to help you to help me!

The S6 doesn't have a screen as such, control is completely via the app, so I can't follow those instructions - although I remember them from the previous model.

The closest I can find in the app is 'Inverter Version', which then has 1D0010-62000d after it.

Would that be what you're looking for?

**Comment by Webreaper** [comment]
That's perfect.

I've finished my gardening for today. 😁👌

**Comment by fboundy** [comment]
Hi guys. Looks like you’ve found what you were looking for in my HomeAssistant code.

I’ve written something very similar in Home Assistant here: https://github.com/fboundy/pv_opt and I’m currently converting it to a full blown Home Assistant integration.

Interestingly your optimisation algorithm appears to use very similar logic to mine. 

Have you considered adding direct control of the inverter via TCP/Modbus? It’s pretty straightforward in Python - no idea how hard it would be in C.

**Comment by Webreaper** [comment]
Most of these algorithms are "charge when it's cheapest, plus some other tweaks". 😁

Haven't looked at Modbus - I'm more interested in the vanilla Soliscloud connection (my understanding is that if you use Modbus it prevents you using Soliscloud).

I think I'm understanding your python code - will have a go at an implementation on Monday.

Cheers
Mark

**Comment by fboundy** [comment]
I think for most folk the cloud API version is fine - local Modbus does seem to clash with the API unless you add extra hardware.

Let me know if anything isn’t clear in the Python code

**Comment by Webreaper** [comment]
@martinpike69 Just successfully test-charged your inverter for 5 minutes.... :)

```
[12:50:12.241--INF] Refreshed state: SOC = 18%, Current PV = 1.625kW, House Load = 1.072kW, Forecast today: 12.04430kWh, tomorrow: 19.53935kWh
[12:50:12.243--INF] Updating inverter time to avoid drift...
[12:50:12.243--INF] Simulated inverter control request: { inverterSn = 1031150234140015, cid = 56, value = 2025-02-24 12:50:12 }
[12:50:20.826--INF] Saving config to server...
[12:50:20.953--INF] Retrieved 12 rates from Octopus (25-Feb-2025 22:00 - 24-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[12:50:25.597--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[12:50:25.598--INF] Enriching history with PV yield for 2 days
[12:50:25.950--INF] Retrieved 153 inverter stats for 24-Feb-2025
[12:50:25.978--INF] Starting test charge for 5 minutes
[12:50:30.791--INF] Setting charge Amps to 75A for slot 1
[12:50:35.449--INF] Setting charge Amps to 100% for slot 1
[12:50:38.717--INF] Setting charge time to 12:50-12:55 for slot 1
[12:55:00.442--INF] Refreshed state: SOC = 22%, Current PV = 1.651kW, House Load = 2.876kW, Forecast today: 12.04430kWh, tomorrow: 19.53935kWh
```
Note the SOC goes from 18% => 22%. :)

This is good progress - I just need to do more testing and tidy the code up and I should have a working version for you to beta-test soon....

@fboundy  - you can ignore the above post, I think I've got it now. Thanks for your assistance with this!

**Comment by martinpike69** [comment]
Ah, that will explain why my SolisCloud has been playing silly buggers over the past 30 mins or so?!

:-)

**Comment by Webreaper** [comment]
Oh, sorry, yes.... 😁

**Comment by Webreaper** [comment]
BTW, I think you had slot 1 set to charge from 21:00 - 22:30, @ 75% or something - you'll need to reset it.

**Comment by fboundy** [comment]
Yep - looks right to me.

**Comment by fboundy** [comment]
Out of interest, where do you get your forecast PV generation from?

Also, for Agile, you might want to use my agilepredict.com API to get predicted prices

**Comment by Webreaper** [comment]
PV forecast comes from Solcast. There's basically two providers:
 
* https://forecast.solar/
* https://solcast.com/

I use solcast because it's pretty easy, but also gives 30-minute predictions for free, for up to 2 strings (with a rooftop hobbyist account). Forecast.Solar isn't so good for free.

Thanks for the agilepredict suggestion, but I'm not planning to integrate agile prediction into the app right now (or, probably, ever 😆 )

**Comment by Webreaper** [comment]
@martinpike69 if you want to give this version a go, I think it should work, mostly?

https://github.com/Webreaper/SolisAgileManager/actions/runs/13500336045

Can you try: 
1. Test charge from the settings screen
2. Test discharge using the manual overrides
3. If those work, let it run for a bit and see if it works and does something sensible.

**Comment by martinpike69** [comment]
Sure. When I updated last time I lost all my login data to Solcast / Solis / Octopus.

Am I best to switch the PI off and on again, and download the new version?  Then extract it to which folder please?  And to not overwrite files - as I assume this is how I lost my logins last time?

Thanks,

Martin

**Comment by Webreaper** [comment]
Just extract to copy over the old files. If you're worried about losing
your login data, copy the config folder somewhere else, and restore it
after the copy is complete.

You should be able to use the "shutdown" option on the Tools page, you
shouldn't need to power cycle the Pi.

**Comment by martinpike69** [comment]
I still don't have the Shutdown option on the Tools page?

Just Charge / Discharge and Dump and Recharge?

**Comment by Webreaper** [comment]
Did you ever upgrade to the latest dev build? If not, you won't have it....

Upgrade today, and use the shutdown commands that Derek posted in the IOG thread, and you'll have it after that.

**Comment by martinpike69** [comment]
I'm clearly doing something wrong. I have a folder called SolisAgileManager, and under that another one called SolisManager-raspi.  I then have the new version - SolisManager-raspi-1.0.412-ev.zip.zip -  in my Downloads folder. Which of the Solis folders am I extracting the downloaded file to please?

**Comment by Webreaper** [comment]
I suspect you have:

  `./SolisManager/SolisManager-raspi`

So you need to:

* Extract the `SolisManager-raspi-1.0.412-ev.zip.zip` into a temporary folder
* Then copy the contents of that folder (which should be around 100 files etc) into the `./SolisManager/SolisManager-raspi` folder.

**Comment by martinpike69** [comment]
I now have the Restart option.

5 minute test charge from Settings screen has worked.

Manual Charge from Home Screen seems to work

Manual Discharge **doesn't** seem to work?  Is this meant to in effect dump as much battery as possible, exporting anything the house isn't using?

**Comment by Webreaper** [comment]
> I now have the Restart option.
> 5 minute test charge from Settings screen has worked.
> Manual Charge from Home Screen seems to work

Hoorah!

> Manual Discharge doesn't seem to work? Is this meant to in effect dump as much battery as possible, exporting anything the house isn't using?

Yes, that's what's supposed to happen. It might be that I haven't got the new API quite right for the discharge. I'll take a look at that tonight, but the rest sounds promising. :)

**Comment by martinpike69** [comment]
Have you got any plans to amend the Price (p/kWh) on the Home Screen to reflect 7p / Off Peak as and when a cheap daytime slot is scheduled under IOG?  I do of course appreciate that this is an Agile focussed system...

**Comment by Webreaper** [comment]
Can you send me a screenshot of what you mean? 

The off-peak (overnight) price for IOG should show correctly, because that's returned from the tariff data. 

For the IOG smart-charge dispatches I don't get any information about the price, so can't display anything there unless I hard-code it....

**Comment by martinpike69** [comment]
Ah, I understand. I assumed that a smart charge dispatch would also come with some sort of 'off peak' indicator, even if not a price.  No problem.  If would probably set some minds at rest if the 'Peak' word was hard coded to change to Off Peak during any smart charge periods though?  Completely up to you.

**Comment by Webreaper** [comment]
Yes, you're right, the price-type should switch to 'off-peak' when an IOG dispatch is in-flight (I thought I'd done that, actually).

**Comment by Webreaper** [comment]
Just checked the code - if the car icon is displaying, the price indicator should change from 'Peak' to 'EV Charge'. Is that not happening?

**Comment by Webreaper** [comment]
> Manual Discharge doesn't seem to work? Is this meant to in effect dump as much battery as possible, exporting anything the house isn't using?

By the way, when you tried this, what was your SOC? It won't let you discharge below a certain level.

**Comment by Webreaper** [comment]
@fboundy I can't spot anything wrong with my Discharge code, it looks like it should work. Is there anything special that needs to be done for the Discharge control - like set the amps to negative or anything odd like that?

**Comment by Webreaper** [comment]
Okay. Might try some test discharges tomorrow, if that's okay? (only a couple of minutes, once I get it to work).

**Comment by fboundy** [comment]
Not that I recall. Are you setting the Volts for each slot (in the new FW)

________________________________

**Comment by Webreaper** [comment]
> Not that I recall. Are you setting the Volts for each slot (in the new FW)

I'm setting the Amps. Or is there a Volts setting separate from the amps?

**Comment by Webreaper** [comment]
Okay, I'm still struggling to figure out what's wrong with the discharge settings. 

Currently I do this when charging:
- Set the charge SOC % to 100%
- Set the discharge SOC % to 15%
- Set charge time to (say) 21:30-22:00
- Set charge amps to 75A
- Set discharge time to 00:00-00:00
- Set discharge amps to 0

And I do this for discharging:
- Set the charge SOC % to 100%
- Set the discharge SOC % to 15%
- Set charge time to 00:00-00:00
- Set charge amps to 0
- Set Discharge time to (say) 21:30-22:00
- Set discharge amps to 75A

I wonder if the problem is that I'm setting the charge SOC % to 100%, which is setting a charge target - is this conflicting with the discharge? Should I set the Charge SOC to 15% or clear it somehow?

**Comment by fboundy** [comment]
There is in the new Firmware but there is no documentation as to what it does! My recollection is that the app sets it low (49.5v) on charge but I can’t remember if it is high on discharge. Will check when I have time

**Comment by Webreaper** [comment]
Okay, looks like I was right. If you set a discharge time, and set the discharge amps to (say) 50A, and you have a ChargeSOC of 100%, then nothing happens. 

If I change it so that the charge time and discharge amps are set, and then change the ChargeSOC to 15%, it discharges.

Thanks to @martinpike69 for letting me test with his inverter (I've stopped buggering about now). If you want to try a build which should now be fully functional for charge, discharge, and 'do nothing', try this: https://github.com/Webreaper/SolisAgileManager/actions/runs/13515324000
The only function I haven't explicitly tested is 'hold'.

**Comment by martinpike69** [comment]
I've just managed to install - at the second attempt, I forgot to reboot my PI first time - the latest dev version.

I've also reinstated Solcast, which seems to be pulling data in.

I'll be plugging in the car later today, when I'll have a look for a car icon or similar on the Home screen.

Thank you so much!

**Comment by Webreaper** [comment]
Great. Let me know if discharge works for you too - I did try it, but it's easier to debug if you can go to the inverter and see what it's doing live on the screen. :)

**Comment by martinpike69** [comment]
Not sure my system is working.

I plugged my car in at 0930, and it's charging.

We're now 0938 and my house battery isn't charging.  I thought the calls to Octopus were every 5 mins?

Have I misunderstood something?  If I have, please explain.  If I haven't, should I send you the log file for today?

Thanks,

Martin

**Comment by martinpike69** [comment]
Still not charging at 0945, so I pressed the Charge icon under Manual Actions.  That doesn't seem to have worked either.

**Comment by martinpike69** [comment]
Sorry, forget the above two comments - user error my end!!

**Comment by Webreaper** [comment]
So it's all working? 😁

**Comment by martinpike69** [comment]
Actually, no, sorry!

Re-plugged in at 0950, got given immediate charge slot. Now 10am, and house battery not charging. I can see that an update re rates has been received from Octopus.

Log file attached.

**Comment by martinpike69** [comment]
I tried to attach it...

[SolisManager-20250225.log](https://github.com/user-attachments/files/18961998/SolisManager-20250225.log)

**Comment by martinpike69** [comment]
And Manual Charge and Discharge don't seem to be working either.  Sorry!

**Comment by Webreaper** [comment]
Debugging and testing now - your inverter might do some stuff. :)

**Comment by martinpike69** [comment]
If you can leave it until 11am if at all possible please?  I'm currently recharging the house batteries...

**Comment by Webreaper** [comment]
Sorry, missed this message - I ran a test charge which seemed to work, but may be because you were already charging. I'll leave it for a bit.

**Comment by fboundy** [comment]
When changing leave the discharge setting off and vice versa. To do this I set start and end times the same.

**Comment by Webreaper** [comment]
> When changing leave the discharge setting off and vice versa. To do this I set start and end times the same.
> […](#)

Yeah, I'm doing that already - if I'm charging I set the discharge start/end times as 00:00, and for a discharge I set the charge start/end times to be 00:00. But it still seems that if you want to discharge, and you have a 00:00-00:00 charge time set, but the Charge SOC is 100%, the inverter won't discharge. If I set the charge SOC to 15%, it then discharges...

**Comment by Webreaper** [comment]
@martinpike69 I just did some testing, and from what I can see it's working. Here's the log:

```
[11:40:51.273--INF] ===========================================================
[11:40:51.294--INF] Application started. Build version v1.0.0.0 Logs being written to ./config
[11:40:51.468--INF] Loaded cached Solcast data from ./config/Solcast-cache.json
[11:40:52.361--INF] Now listening on: http://localhost:5158
[11:40:52.362--INF] Application started. Press Ctrl+C to shut down.
[11:40:52.362--INF] Hosting environment: Development
[11:40:52.362--INF] Content root path: /Users/markotway/LocalCloud/Development/SolisAgileManager/SolisAgileManager/SolisManager
[11:40:53.105--INF] Retrieved 12 rates from Octopus (26-Feb-2025 22:00 - 25-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[11:40:53.109--INF] 73 new Octopus rates available to 27-Feb-2025 00:00 (cheapest: 13.24239p/kWh, peak: 40.504905p/kWh)
[11:40:53.120--INF] Loaded 1234 entries from execution history file SolisManagerExecutionHistory.csv
[11:40:53.148--WRN] SOC is zero, so skipping charge if low battery due to bad inverter state data
[11:40:53.149--WRN] SOC is zero, so skipping maintain charge rule due to bad inverter state data
[11:40:57.209--INF] Detected new firmware version: 43605 (AA55)
[11:40:59.166--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[11:40:59.185--INF] Enriching history with PV yield for 2 days
[11:40:59.550--INF] Retrieved 135 inverter stats for 25-Feb-2025
[11:40:59.994--INF] Retrieved 264 inverter stats for 13-Feb-2025
[11:41:00.163--INF] Refreshed state: SOC = 42%, Current PV = 3.347kW, House Load = 5.968kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:41:00.165--INF] Updating inverter time to avoid drift...
[11:41:00.167--INF] Simulated inverter control request: { inverterSn = 1031150234140015, cid = 56, value = 2025-02-25 11:41:00 }
[11:41:19.973--INF] Saving config to server...
[11:41:20.083--INF] Retrieved 12 rates from Octopus (26-Feb-2025 22:00 - 25-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[11:41:21.694--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[11:41:21.699--INF] Enriching history with PV yield for 2 days
[11:41:22.065--INF] Retrieved 135 inverter stats for 25-Feb-2025
[11:41:32.337--INF] Updating slot action for 02/25/2025 11:30:00 to Charge...
[11:41:32.341--INF] Set override: 11:30 - Charge
[11:41:34.082--INF] Sending new charge instruction to Solis Inverter: 75, 0, 11:30-12:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[11:45:00.708--INF] Refreshed state: SOC = 43%, Current PV = 2.453kW, House Load = 5.872kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:50:00.578--INF] Refreshed state: SOC = 45%, Current PV = 2.389kW, House Load = 7.177kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:50:05.123--INF] Updating slot action for 02/25/2025 11:30:00 to DoNothing...
[11:50:05.123--INF] Cleared override: 11:30 - DoNothing
[11:50:10.429--INF] Sending new charge instruction to Solis Inverter: 0, 0, 00:00-00:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[11:55:00.665--INF] Refreshed state: SOC = 43%, Current PV = 2.296kW, House Load = 9.408kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
```
If you look at the `Refreshed State` log entries for `11:41:00`, `11:45:00` and `11:50:00`, you can see that the battery was indeed charging - it went from 42% => 45%. This despite the fact that your house load is a whopping 9.4kW, of which only around 2-3kW is being supplied from PV. 

So it looks like charging is working. I haven't tried discharge, because a) that's less critical, and b) it'll be difficult to tell if it's working because the house load and PV are high at the moment. We can try that another time.

So when you said "Manual Charge and Discharge don't seem to be working" we need to understand what's happening there. 

Let's focus on that for the moment and ignore the IOG smart-charge - we've already seen from Derek's experiences that sometimes even though your EV is charging, Octopus don't send a smart-charge notification so SolisManager may not get notified and won't attempt to charge the inverter/battery. In the log you sent 2 hours ago there certainly weren't any IOG dispatches picked up by SolisManager, so I don't think they were sent from Octopus. If you don't see a car icon instead of the lightning icon, then the IOG notification hasn't come through from Octopus.

Once we've established that the changes for the new firmware are working as expected (and from my end, that looks to be the case) then you can run for a few days and see if the IOG Dispatches start showing up.

**Comment by martinpike69** [comment]
Now heading out, but I did a charge via SolisCloud when this system didn't work.
We often have a high load.  ASHP, immersion, EV charging, cooking etc.
Have you seen the new email from Ohme?  Implementing an end time of 4am to 11am, like all other IOG integrations.

Thanks and regards,
Martin 

    On Tuesday, 25 February 2025 at 12:07:06 GMT, Mark Otway ***@***.***> wrote:  
 
  
@martinpike69 I just did some testing, and from what I can see it's working. Here's the log:
[11:40:51.273--INF] ===========================================================
[11:40:51.294--INF] Application started. Build version v1.0.0.0 Logs being written to ./config
[11:40:51.468--INF] Loaded cached Solcast data from ./config/Solcast-cache.json
[11:40:52.361--INF] Now listening on: http://localhost:5158
[11:40:52.362--INF] Application started. Press Ctrl+C to shut down.
[11:40:52.362--INF] Hosting environment: Development
[11:40:52.362--INF] Content root path: /Users/markotway/LocalCloud/Development/SolisAgileManager/SolisAgileManager/SolisManager
[11:40:53.105--INF] Retrieved 12 rates from Octopus (26-Feb-2025 22:00 - 25-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[11:40:53.109--INF] 73 new Octopus rates available to 27-Feb-2025 00:00 (cheapest: 13.24239p/kWh, peak: 40.504905p/kWh)
[11:40:53.120--INF] Loaded 1234 entries from execution history file SolisManagerExecutionHistory.csv
[11:40:53.148--WRN] SOC is zero, so skipping charge if low battery due to bad inverter state data
[11:40:53.149--WRN] SOC is zero, so skipping maintain charge rule due to bad inverter state data
[11:40:57.209--INF] Detected new firmware version: 43605 (AA55)
[11:40:59.166--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[11:40:59.185--INF] Enriching history with PV yield for 2 days
[11:40:59.550--INF] Retrieved 135 inverter stats for 25-Feb-2025
[11:40:59.994--INF] Retrieved 264 inverter stats for 13-Feb-2025
[11:41:00.163--INF] Refreshed state: SOC = 42%, Current PV = 3.347kW, House Load = 5.968kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:41:00.165--INF] Updating inverter time to avoid drift...
[11:41:00.167--INF] Simulated inverter control request: { inverterSn = 1031150234140015, cid = 56, value = 2025-02-25 11:41:00 }
[11:41:19.973--INF] Saving config to server...
[11:41:20.083--INF] Retrieved 12 rates from Octopus (26-Feb-2025 22:00 - 25-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[11:41:21.694--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[11:41:21.699--INF] Enriching history with PV yield for 2 days
[11:41:22.065--INF] Retrieved 135 inverter stats for 25-Feb-2025
[11:41:32.337--INF] Updating slot action for 02/25/2025 11:30:00 to Charge...
[11:41:32.341--INF] Set override: 11:30 - Charge
[11:41:34.082--INF] Sending new charge instruction to Solis Inverter: 75, 0, 11:30-12:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[11:45:00.708--INF] Refreshed state: SOC = 43%, Current PV = 2.453kW, House Load = 5.872kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:50:00.578--INF] Refreshed state: SOC = 45%, Current PV = 2.389kW, House Load = 7.177kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:50:05.123--INF] Updating slot action for 02/25/2025 11:30:00 to DoNothing...
[11:50:05.123--INF] Cleared override: 11:30 - DoNothing
[11:50:10.429--INF] Sending new charge instruction to Solis Inverter: 0, 0, 00:00-00:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[11:55:00.665--INF] Refreshed state: SOC = 43%, Current PV = 2.296kW, House Load = 9.408kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh

If you look at the Refreshed State log entries for 11:41:00, 11:45:00 and 11:50:00, you can see that the battery was indeed charging - it went from 42% => 45%. This despite the fact that your house load is a whopping 9.4kW, of which only around 2-3kW is being supplied from PV.

So it looks like charging is working. I haven't tried discharge, because a) that's less critical, and b) it'll be difficult to tell if it's working because the house load and PV are high at the moment. We can try that another time.

So when you said "Manual Charge and Discharge don't seem to be working" we need to understand what's happening there.

Let's focus on that for the moment and ignore the IOG smart-charge - we've already seen from Derek's experiences that sometimes even though your EV is charging, Octopus don't send a smart-charge notification so SolisManager may not get notified and won't attempt to charge the inverter/battery. In the log you sent 2 hours ago there certainly weren't any IOG dispatches picked up by SolisManager, so I don't think they were sent from Octopus. If you don't see a car icon instead of the lightning icon, then the IOG notification hasn't come through from Octopus.

Once we've established that the changes for the new firmware are working as expected (and from my end, that looks to be the case) then you can run for a few days and see if the IOG Dispatches start showing up.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
Webreaper left a comment (Webreaper/SolisAgileManager#119)
@martinpike69 I just did some testing, and from what I can see it's working. Here's the log:
[11:40:51.273--INF] ===========================================================
[11:40:51.294--INF] Application started. Build version v1.0.0.0 Logs being written to ./config
[11:40:51.468--INF] Loaded cached Solcast data from ./config/Solcast-cache.json
[11:40:52.361--INF] Now listening on: http://localhost:5158
[11:40:52.362--INF] Application started. Press Ctrl+C to shut down.
[11:40:52.362--INF] Hosting environment: Development
[11:40:52.362--INF] Content root path: /Users/markotway/LocalCloud/Development/SolisAgileManager/SolisAgileManager/SolisManager
[11:40:53.105--INF] Retrieved 12 rates from Octopus (26-Feb-2025 22:00 - 25-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[11:40:53.109--INF] 73 new Octopus rates available to 27-Feb-2025 00:00 (cheapest: 13.24239p/kWh, peak: 40.504905p/kWh)
[11:40:53.120--INF] Loaded 1234 entries from execution history file SolisManagerExecutionHistory.csv
[11:40:53.148--WRN] SOC is zero, so skipping charge if low battery due to bad inverter state data
[11:40:53.149--WRN] SOC is zero, so skipping maintain charge rule due to bad inverter state data
[11:40:57.209--INF] Detected new firmware version: 43605 (AA55)
[11:40:59.166--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[11:40:59.185--INF] Enriching history with PV yield for 2 days
[11:40:59.550--INF] Retrieved 135 inverter stats for 25-Feb-2025
[11:40:59.994--INF] Retrieved 264 inverter stats for 13-Feb-2025
[11:41:00.163--INF] Refreshed state: SOC = 42%, Current PV = 3.347kW, House Load = 5.968kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:41:00.165--INF] Updating inverter time to avoid drift...
[11:41:00.167--INF] Simulated inverter control request: { inverterSn = 1031150234140015, cid = 56, value = 2025-02-25 11:41:00 }
[11:41:19.973--INF] Saving config to server...
[11:41:20.083--INF] Retrieved 12 rates from Octopus (26-Feb-2025 22:00 - 25-Feb-2025 13:00) for product E-1R-COSY-22-12-08-J
[11:41:21.694--INF] Inverter already in correct state (0, 0, 00:00-00:00, 00:00-00:00) so no charge instructions need to be applied
[11:41:21.699--INF] Enriching history with PV yield for 2 days
[11:41:22.065--INF] Retrieved 135 inverter stats for 25-Feb-2025
[11:41:32.337--INF] Updating slot action for 02/25/2025 11:30:00 to Charge...
[11:41:32.341--INF] Set override: 11:30 - Charge
[11:41:34.082--INF] Sending new charge instruction to Solis Inverter: 75, 0, 11:30-12:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[11:45:00.708--INF] Refreshed state: SOC = 43%, Current PV = 2.453kW, House Load = 5.872kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:50:00.578--INF] Refreshed state: SOC = 45%, Current PV = 2.389kW, House Load = 7.177kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh
[11:50:05.123--INF] Updating slot action for 02/25/2025 11:30:00 to DoNothing...
[11:50:05.123--INF] Cleared override: 11:30 - DoNothing
[11:50:10.429--INF] Sending new charge instruction to Solis Inverter: 0, 0, 00:00-00:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[11:55:00.665--INF] Refreshed state: SOC = 43%, Current PV = 2.296kW, House Load = 9.408kW, Forecast today: 12.10745kWh, tomorrow: 4.93330kWh

If you look at the Refreshed State log entries for 11:41:00, 11:45:00 and 11:50:00, you can see that the battery was indeed charging - it went from 42% => 45%. This despite the fact that your house load is a whopping 9.4kW, of which only around 2-3kW is being supplied from PV.

So it looks like charging is working. I haven't tried discharge, because a) that's less critical, and b) it'll be difficult to tell if it's working because the house load and PV are high at the moment. We can try that another time.

So when you said "Manual Charge and Discharge don't seem to be working" we need to understand what's happening there.

Let's focus on that for the moment and ignore the IOG smart-charge - we've already seen from Derek's experiences that sometimes even though your EV is charging, Octopus don't send a smart-charge notification so SolisManager may not get notified and won't attempt to charge the inverter/battery. In the log you sent 2 hours ago there certainly weren't any IOG dispatches picked up by SolisManager, so I don't think they were sent from Octopus. If you don't see a car icon instead of the lightning icon, then the IOG notification hasn't come through from Octopus.

Once we've established that the changes for the new firmware are working as expected (and from my end, that looks to be the case) then you can run for a few days and see if the IOG Dispatches start showing up.

**Comment by Webreaper** [comment]
> Now heading out, but I did a charge via SolisCloud when this system didn't work.

Don't understand this comment. 

> We often have a high load.  ASHP, immersion, EV charging, cooking etc.

Yeah, us too. That's fine, it just means dicharge isn't always obvious since the battery is probably being chewed up anyway. But like I say, we can ignore testing manual discharge as it's an edge case and isn't really important unless Agile price go negative.... 😄 

>  Have you seen the new email from Ohme?  Implementing an end time of 4am to 11am, like all other IOG integrations.

Email? Not sure what you mean. I wouldn't see any emails from your Ohme charger. The only notifications that I (or SolisManager) will see are those provided by the Octopus API...

Let's catch up later...

**Comment by martinpike69** [comment]
I just meant that when pressing Charge under Manual Actions didn't work, I did it via soliscloud.
M

Yahoo Mail – Email Simplified 
 
  On Tue, 25 Feb 2025 at 12:42, Mark ***@***.***> wrote:    

Now heading out, but I did a charge via SolisCloud when this system didn't work.


Don't understand this comment.


We often have a high load.  ASHP, immersion, EV charging, cooking etc.


Yeah, us too. That's fine, it just means dicharge isn't always obvious since the battery is probably being chewed up anyway. But like I say, we can ignore testing manual discharge as it's an edge case and isn't really important unless Agile price go negative.... 😄


Have you seen the new email from Ohme?  Implementing an end time of 4am to 11am, like all other IOG integrations.


Email? Not sure what you mean. I wouldn't see any emails from your Ohme charger. The only notifications that I (or SolisManager) will see are those provided by the Octopus API...

Let's catch up later...

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
Webreaper left a comment (Webreaper/SolisAgileManager#119)

Now heading out, but I did a charge via SolisCloud when this system didn't work.


Don't understand this comment.


We often have a high load.  ASHP, immersion, EV charging, cooking etc.


Yeah, us too. That's fine, it just means dicharge isn't always obvious since the battery is probably being chewed up anyway. But like I say, we can ignore testing manual discharge as it's an edge case and isn't really important unless Agile price go negative.... 😄


Have you seen the new email from Ohme?  Implementing an end time of 4am to 11am, like all other IOG integrations.


Email? Not sure what you mean. I wouldn't see any emails from your Ohme charger. The only notifications that I (or SolisManager) will see are those provided by the Octopus API...

Let's catch up later...

**Comment by Webreaper** [comment]
Yeah, it's a bit odd. I've updated the logging, next time you're available if you can update to this build it might give us a clue... https://github.com/Webreaper/SolisAgileManager/actions/runs/13519344326

**Comment by Webreaper** [comment]
> I started a charge, and can see from the log that 74 rates were pulled in. But no automated charge was started.

Those 74 rates are just the next 37 hours-worth of Octopus 30-minute price slots. That's nothing to do with IOG smart-chargees.

If Octopus sends you a smart-charge slot you'll see something like this in the logs:
```
Found 2 IOG Smart-Charge slots (out of a total of 2 planned and 3 completed dispatches)"
   Time: 16:34 - 17:26, Type: smart-charge, Delta: -7"
   Time: 18:22 - 18:55, Type: smart-charge, Delta: -9"
```
In the above case, you'd see the slots in the Charging plan change to a car icon for:
- 16:30-17:00
- 17:00-17:30
- 18:00-18:30
- 18:30-19:00

If none of the above happens, then Octopus hasn't generated an IOG smart-charge slot for you, in which case SolisManager won't do anything special and will just follow the normal charging plan....

**Comment by Webreaper** [comment]
BTW, unrelated to IOG smart charging, there's a couple of interesting log entries in that log: 
```
[16:39:50.014--WRN] No data returned reading control state (CID = "ChargeSlot1_Time")
[16:39:50.015--WRN] Inverter control request did not stick: CID: "ChargeSlot1_Time", Value: 16:30-17:00
```
This implies that SolisManager attempted to set the `ChargeSlot1_Time` value on the inverter, but when it queried the value back to check, the new value wasn't there. This means that sending that instruction to the inverter didn't save it properly (or reading it back didn't read it properly).

I think @fboundy said this is a problem, particularly with the new firmware, so I'll look to put some retries in there....

**Comment by martinpike69** [comment]
> > I started a charge, and can see from the log that 74 rates were pulled in. But no automated charge was started.
> 
> Those 74 rates are just the next 37 hours-worth of Octopus 30-minute price slots - which is normal for any tariff (Agile, Cosy, IOG etc). That's nothing to do with IOG smart-chargees.
> 
> If Octopus sends you a smart-charge slot you'll see something like this in the logs:
> 
> ```
> Found 2 IOG Smart-Charge slots (out of a total of 2 planned and 3 completed dispatches)"
>    Time: 16:34 - 17:26, Type: smart-charge, Delta: -7"
>    Time: 18:22 - 18:55, Type: smart-charge, Delta: -9"
> ```
> 
> In the above case, you'd see the slots in the Charging plan change to a car icon for:
> 
> * 16:30-17:00
> * 17:00-17:30
> * 18:00-18:30
> * 18:30-19:00
> 
> If none of the above happens, then Octopus hasn't generated an IOG smart-charge slot for you, in which case SolisManager won't do anything special and will just follow the normal charging plan....

OK, so we're somewhat at a stalemate here?

I unplugged my car, waited a couple of minutes, and plugged it in again.  I was given an immediate slot, running through to tomorrow morning.

I'm looking at my Ohme app, and it says I'm Smart Charging. I can also see from the lights on my car that it's charging, and I can see from my house CT clamp that its charging.

What we're not getting is those Dispatches from Octopus it seems?

Log attached again.

Cheers,

Martin

[SolisManager-20250225.log](https://github.com/user-attachments/files/18969344/SolisManager-20250225.log)

**Comment by martinpike69** [comment]
FYI - I have set Charge via Manual Actions for 1700-1730 and 1730-1800.

**Comment by Webreaper** [comment]
Just out of interest - were you originally with Bulb and then got bumped over to Octopus when they went bust? I think that's where the `BB` tariff codes come from....

**Comment by martinpike69** [comment]
> Just out of interest - were you originally with Bulb and then got bumped over to Octopus when they went bust? I think that's where the `BB` tariff codes come from....

Yes.

**Comment by martinpike69** [comment]
> One other thing - before you upgrade to that latest build. Do you have the checkbox in the settings that says "Intelligent Go Charging"? I suspect you don't.....

Correct, no check box

**Comment by martinpike69** [comment]
The new version won't Initialise - just says Initialising in the middle of the screen?

Log attached.

[SolisManager-20250225.log](https://github.com/user-attachments/files/18970016/SolisManager-20250225.log)

**Comment by Webreaper** [comment]
It's running fine. Just hold shift and click refresh in the browser.

**Comment by martinpike69** [comment]
Sorry, that's not working. I tried rebooting as well.

**Comment by Webreaper** [comment]
Can you resend the updated logs?

**Comment by Webreaper** [comment]
Possibly a bug in the retry logic is looping. Try this one, where I've reverted that change https://github.com/Webreaper/SolisAgileManager/actions/runs/13528060649

**Comment by martinpike69** [comment]
Installed, and up and running again.

IOG check box present and ticked.

**Comment by Webreaper** [comment]
Woot.

Sorry for the bug. That's what happens when I'm juggling this, work and several other things!

**Comment by Webreaper** [comment]
BTW @martinpike69 - can you try a manual discharge at some point? If it works, I can close this issue.

**Comment by martinpike69** [comment]
I'll try a manual discharge tomorrow, when I hope to have some spare battery.

But I've plugged the car in again this evening, received slots, and they're still not coming through on the Home screen or the log?

[SolisManager-20250225.log](https://github.com/user-attachments/files/18972888/SolisManager-20250225.log)

**Comment by Webreaper** [comment]
It says it's picked up some completed slots, so that bit is working.

ISTR that late in the evening you can get charge slots, but they're not smart-charge ones. So let's see if it looks better tomorrow. Derek Johnson has something similar to what you're seeing there.

**Comment by martinpike69** [comment]
Any slot outside 2330 to 0530 is a smart charging slot

**Comment by Webreaper** [comment]
Sure, but I don't make the rules. If Octopus send it to us as a non-smart charge slot, there's not much we can do....

**Comment by martinpike69** [comment]
Sure, understood.

There's a lot of hoo ha flying about at the moment on Ohme / IOG groups, as it seems that that Ohme were the only integration that allowed you to set a 'finish' time outside of 0400 to 1100.

This loophole is being closed from tomorrow.

Notwithstanding that, the IOG T&C's have always referred to Fair Use, and reserve the right to bill any Smart Charging beyond 6 hours a day at Full Rate.  To my knowledge, this has never actually happened to anyone - so far.

But I do wonder whether it's been considered that sending a Smart Charge dispatch outside of 2330 - 0530, and then billing for it later at Full Rate, might be considered as confusing, and potentially unlawful.

All of this is conjecture of course.

Short of calling or emailing Octopus (or Ohme?), how can we resolve this?

Cheers,

Martin

**Comment by Webreaper** [comment]
> Short of calling or emailing Octopus (or Ohme?), how can we resolve this?

No idea. It's not really an issue for me or the app. 

You and other IOG customers would need to work with Octopus to have the smart-charge dispatches work as expected, and presented to 3rd-party apps via the API. But that's far outwith the scope of this project (and wouldn't require any code-changes from my side). This sounds like an Octopus issue rather than an Ohme issue to me, but TBH, as somebody without an EV or charger, I don't have skin in this particular game.

So I think the summary is:

1. The new firmware changes are now working (pending confirmation of discharge working) - so I should be able to close this issue.
2. The IOG smart-charge slots are working (notwithstanding the fact that Octopus may not be issuing smart-charge slots according to their T&Cs etc), at which point I can close #107 

Once both are closed, I'll do a proper release, maybe later today if the discharge looks good.

**Comment by martinpike69** [comment]
Hi Mark,

That's completely fair. I'm sure it's as frustrating for you to have done this work only to discover that some expected information isn't being received, as it is for me to get so close to automating a boring manual task, but for it to not quite happen.

Just so I can be clear though, is this just an issue for me as an Ohme owner using the latest API, or is this also the case for Derek, the other Ohme owner using the older API?

I'll check the manual discharge shortly. My house is pulling maximum from the battery at the moment.

Thanks again for all your help on this.

Cheers,

Martin

**Comment by martinpike69** [comment]
I don't think the Manual Discharge worked - log attached.

[SolisManager-20250226.log](https://github.com/user-attachments/files/18980328/SolisManager-20250226.log)

**Comment by Webreaper** [comment]
> I was under the impression that Derek had received some Smart Charge dispatches outside of 2330-0530?

Yes, he did. And at least one other person has had this work. However, 

* The first time @dqj999 tried it he didn't get any slots despite charging, there was some nuance...
* As you say, it's possible Octopus may already be restricting it. 

But according to the new T&Cs you should still get some charging slots in the day, just not during the very peak times, if I'm reading it right. I guess we see over the next few days.... 

> I don't think the Manual Discharge worked - log attached.

Looks like the setting didn't persist in the inverter: 
```
[08:36:51.305--WRN] No data returned reading control state (CID = "DischargeSlot1_Amps")
[08:36:51.306--WRN] Inverter control request did not stick: CID: "DischargeSlot1_Amps", Value: 95
```
If you have time, if you could try this build it would be good: https://github.com/Webreaper/SolisAgileManager/actions/runs/13540949130 - it has retry logic that's better than last time. ;)

**Comment by martinpike69** [comment]
New build installed.

Manual Discharge pressed at 1027. Log attached.  Again, I don't think it worked?  Difficult to tell at my end due to constantly varying loads.

[SolisManager-20250226.log](https://github.com/user-attachments/files/18982127/SolisManager-20250226.log)

**Comment by Webreaper** [comment]
Can you try one more time? I think you set it at 10:27, and it looks like it worked, and then at 10:30 the normal charging plan kicked in and reverted it back to 'do nothing'. 😆 

```
[10:27:15.840--INF] Set override: 10:00 - Discharge
[10:27:19.595--INF] Found 0 IOG Smart-Charge slots (out of a total of 0 planned and 0 completed dispatches)
[10:27:26.573--INF] Sending new charge instruction to Solis Inverter: 0, 95, 00:00-00:00, 10:00-10:30, SOC: 15%, D-SOC: 15%
[10:30:01.034--INF] Retrieved 4 rates from Octopus (27-Feb-2025 23:30 - 26-Feb-2025 23:30) for product E-1R-INTELLI-BB-VAR-23-03-01-A
[10:30:01.040--INF] 48 new Octopus rates available to 28-Feb-2025 05:30 (cheapest: 7.00035p/kWh, peak: 27.102495p/kWh)
[10:30:01.431--INF] Found 0 IOG Smart-Charge slots (out of a total of 0 planned and 0 completed dispatches)
[10:30:04.216--INF] Sending new charge instruction to Solis Inverter: 0, 0, 00:00-00:00, 00:00-00:00, SOC: 100%, D-SOC: 15%
[10:30:08.152--WRN] No data returned reading control state (CID = "ChargeSlot1_Time")
[10:30:08.153--WRN] Inverter control request did not stick: CID: "ChargeSlot1_Time", Value: 00:00-00:00 (attempt: 0)
[10:30:11.484--WRN] No data returned reading control state (CID = "DischargeSlot1_Time")
[10:30:11.484--WRN] Inverter control request did not stick: CID: "DischargeSlot1_Time", Value: 00:00-00:00 (attempt: 0)
```

**Comment by martinpike69** [comment]
Ooooh!

I just plugged the car in, got given a long daytime slot, came back to the PI, and the slots are showing!

The manual discharge will have to wait a while I'm afraid...

**Comment by Webreaper** [comment]
> Ooooh!
> 
> I just plugged the car in, got given a long daytime slot, came back to the PI, and the slots are showing!
> 
> The manual discharge will have to wait a while I'm afraid...

Excellent! Fine to leave the discharge for another day. :)

I might even release as-is, and just fix the discharge in a future release if it's not quite right. Most people won't use it that much...

**Comment by Webreaper** [comment]
> Sorry, log attached, showing Smart Charge slots...
> [SolisManager-20250226.log](https://github.com/user-attachments/files/18982243/SolisManager-20250226.log)

IT'S WORKING!!! 😄

**Comment by martinpike69** [comment]
THANK YOU!

The only slight issue now is that I've just read one persons report (if it's true) that from 1st April their IOG night rate is going from 7p to 13.53p, and day rate from 27.10p to 32.26p.  Which is obviously a very large increase.  

The possible good news though, is that I *could* switch to Agile, which I'd always avoided due to the faff.  From what you've seen on Agile, can you average below the 13.5p mark?

One question re the Solis settings please - why maximum 95 amp charge rate please?

**Comment by Webreaper** [comment]
> The possible good news though, is that I could switch to Agile, which I'd always avoided due to the faff. From what you've seen on Agile, can you average below the 13.5p mark?

For the last 3 months agile has been pants - we were averaging about 18p/kWh until mid-Dec, and then in the last 2 months it was heading over 22p - which was why we switched to Cosy. That's working out much better for us - we charge in the drops (13.4p/kWh) and our battery carries us through until the next drop. So other than a couple of blips, we're basically averaging 13.5p almost all of the time now.

Agile rates are _starting_ to get better now - there were 2 days this week where it would have been marginally cheaper for us to be on Agile than cosy, assuming some judicious charging strategy (if only there was an app for that 🤔 ). But it's worse again today - the peaks are marginally higher than Cosy, but the troughs are much higher too. I've been using the SolisManager comparison graphs daily at the moment.

> One question re the Solis settings please - why maximum 95 amp charge rate please?

No particular reason - just thought that was a sensible Max, but I guess if you have the right battery array configuration, it could be higher. I'll make the max 150A and see what people make of that (I think you're looking for 125A?).

**Comment by Webreaper** [comment]
Fixed to allow up to 150A: https://github.com/Webreaper/SolisAgileManager/actions/runs/13542237708

**Comment by martinpike69** [comment]
S

[SolisManager-20250226.log](https://github.com/user-attachments/files/18982537/SolisManager-20250226.log)

orry, log attached

**Comment by martinpike69** [comment]
Ah, the SolisCloud information on the web and my phone is 25 mins out of date. I assume this is related to us now accessing the account via API?

It still doesn't explain the reducing battery charge info coming via the API though, and conflicting with what I can see from live usage data from the CT.

**Comment by Webreaper** [comment]
It's possible that with all the restarts etc that we've overdone it with the APIs and Soliscloud couldn't get an update. Mind you, the solis rate-limiting is pretty lax, it only blocks if you make > 3 calls per second. Let's see if it settles after a while.

**Comment by martinpike69** [comment]
The Solis data appears to have frozen.

For the last four 5 min increments the data has been identical for Current PV and House Load.  This would be extremely unlikely.

[SolisManager-20250226.log](https://github.com/user-attachments/files/18982736/SolisManager-20250226.log)

**Comment by Webreaper** [comment]
I'm seeing something similar at my end - it's unlikely that the PV and Load would be identical 5 minutes apart, to 3 decimal places...

```
[11:05:00.181--INF] Refreshed state: SOC = 46%, Current PV = 0.300kW, House Load = 1.955kW, Forecast today: 8.01955kWh, tomorrow: 27.19995kWh
[11:10:00.383--INF] Refreshed state: SOC = 46%, Current PV = 0.300kW, House Load = 1.955kW, Forecast today: 8.01955kWh, tomorrow: 27.19995kWh
```

May be an issue at Solis's end. I don't see any errors. They had a big outage earlier this week when SolisCloud didn't load at all, so maybe they've got issues or are doing maintenance.

**Comment by Webreaper** [comment]
5 mins later and still getting the same data....

**Comment by Webreaper** [comment]
Updated correctly now - in line with the actual inverter display.

**Comment by martinpike69** [comment]
I need to head out shortly, so I just Paused the charge on the Ohme app.  This doesn't appear to have resulted in a change to the slots as reported by Octopus - I assume Ohme don't tell them.  However, apparently what happens is that when Ohme do tell Octopus - either at the end of each charge session, or prior to a billing cycle I assume, then you only get the slots where you ACTUALLY CHARGED at the cheap rate.  Clearly there's nothing you can do about this, but it may be worth highlighting that Ohme users shouldn't use the Pause Charge facility.  I've no idea about Zappi, Wallbox etc, or car integrations.

Since writing the above, I've ended the charge, unplugged, and it's been more than 5 minutes, and I can't see any new activity from Octopus in terms of updating the Smart Charge schedule in either the logs or on the Home Screen.

I'll give it a bit longer to see what happens.

**Comment by martinpike69** [comment]
It all seems to have updated now. Future slots back to peak. Note to self, don't be so impatient!

**Comment by martinpike69** [comment]
I've just tested the Manual Discharge feature again.  No luck.  Log attached.

[SolisManager-20250228.log](https://github.com/user-attachments/files/19030366/SolisManager-20250228.log)

**Comment by Webreaper** [comment]
Thanks. Unfortunately I don't think this will count as a valid test - because most of the calls to the Solis API are returning with `502 Bad gateway`, which means that SolisCloud is down or their servers are having problems. 

I've had other users report similar errors today, and I've got at least two `504 Gateway Timeout` errors in my logs this afternoon.

We'll have to wait until it's working reliably for a confirmed test one way or the other!!
