### ISSUE TITLE
Build ARM64 Docker image

### ISSUE THREAD

**Issue by Webreaper** [Webreaper/SolisAgileManager#44]
https://medium.com/medialesson/building-arm64-docker-images-with-net-8-a-quick-solution-5491a94eb507

https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/

**Comment by dqj999** [comment]
I'm trying to download the docker image for the Pi 3, and I'm getting this error.

**docker pull webreaper/solisagilemanager:1.0.170**

1.0.170: Pulling from webreaper/solisagilemanager
no matching manifest for linux/arm/v7 in the manifest list entries

According to Google AI Studio:
That error message "no matching manifest for linux/arm/v7 in the manifest list entries" tells us that the Docker image you're trying to pull (webreaper/solisagilemanager:1.0.170) doesn't have a pre-built version that matches your Raspberry Pi 3's architecture (which is **linux/arm/v7**).

It suggests that the a matching manifest entry would look something like this:

"platform": {
                "architecture": "arm",
                "os": "linux",
                 "variant":"v7"
            }

**Comment by Webreaper** [comment]
Just added a build for linux/arm/7 - let's see if it works. If this completes successfully, you can try pulling `webreaper/solisagilemanager:dev` and see if that works. If it does, I'll do a release with it. 

https://github.com/Webreaper/SolisAgileManager/actions/runs/12845989397

**Comment by Webreaper** [comment]
Okay, that didn't work. I'll need to investigate later....

**Comment by Webreaper** [comment]
Okay, last run worked. Can you try `webreaper:solisagilemanager:dev` and let me know if that works? If it does, I'll release it.

**Comment by dqj999** [comment]
docker pull webreaper/solisagilemanager:dev
dev: Pulling from webreaper/solisagilemanager
af302e5c37e9: Pull complete 
b7f90be4bd50: Pull complete 
56676eeaaf44: Pull complete 
b7db1e46071c: Pull complete 
baddccf2b575: Pull complete 
3820e4df2c07: Pull complete 
4489166a1506: Pull complete 
4f4fb700ef54: Pull complete 
f11235695271: Pull complete 
7fde41d46949: Pull complete 
Digest: sha256:d06e625d2ad17578ae77d158356650ac37a869defaa61b1fab5599ad976ed557
Status: Downloaded newer image for webreaper/solisagilemanager:dev
docker.io/webreaper/solisagilemanager:dev

We're making progress!

**Comment by Webreaper** [comment]
Nice! I've not built for RPi before, so this is a learning experience for me. 😁

**Comment by dqj999** [comment]
Tried running the Image but got this result:

docker -D  -l debug    run  -d webreaper/solisagilemanager:dev 
time="2025-01-19T10:34:47Z" level=debug msg="otel error" error="1 errors occurred detecting resource:\n\t* conflicting Schema URL: https://opentelemetry.io/schemas/1.21.0 and https://opentelemetry.io/schemas/1.26.0"
5de5a8883aed7529817a677d1b16de7cf355efa6983258f0214e809502ed4e09

docker ps -a
CONTAINER ID   IMAGE                             COMMAND                  CREATED             STATUS                           PORTS                               NAMES
5de5a8883aed   webreaper/solisagilemanager:dev   "/app/SolisManager /?"   3 minutes ago       Exited (255) 3 minutes ago                                           sweet_chatelet
4d9be45e5368   webreaper/solisagilemanager:dev   "/app/SolisManager /?"   28 minutes ago      Exited (255) 28 minutes ago

**Comment by Webreaper** [comment]
No idea what any of that means. Sorry. What was your docker command? If it's the one above, then you haven't mapped a folder to the `appdata` dir, which we'll need to see the logs.

**Comment by dqj999** [comment]
I gather that I need to add a -v parameter to the run command. What would be a suitable parameter for the Pi OS?

**Comment by Webreaper** [comment]
Just map the volume to a local folder. Might be easier using docker compose, there's an example in the readme.

**Comment by dqj999** [comment]
I've now got a more basic error message with this command:

docker run -p 5169:5169 webreaper/solisagilemanager:dev

exec /app/SolisManager: no such file or directory

(Without the -d option the error message is listed directly on the console output. )

There is still the other error if I select the -D option

docker -D -l error run -p 5169:5169 webreaper/solisagilemanager:dev
time="2025-01-19T11:54:24Z" level=debug msg="otel error" error="1 errors occurred detecting resource:\n\t* conflicting Schema URL: https://opentelemetry.io/schemas/1.21.0 and https://opentelemetry.io/schemas/1.26.0"
exec /app/SolisManager: no such file or directory
time="2025-01-19T11:54:26Z" level=debug msg="[hijack] End of stdout"

**Comment by Webreaper** [comment]
Interesting. `app/SolisManager` is where the binaries should be. So the
implication is that the RPi build didn't..... build anything.

Thanks, this is useful, looks like I have more work to do on the image
build for RPi. Will take a look tonight.

BTW, I think the OpenTelemetry thing is a warning and not critical.

**Comment by dqj999** [comment]
I think I have a problem Houston. I've just checked what the operating system version is on my Pi 3 and it reports is as 32-bit.

dqj999@raspberrypi:~ $ uname -m
armv7l

armv7l means 32-bit OS: If you are seeing that then your currently installed OS is a 32-bit version.

aarch64 or arm64 means 64-bit OS: If you see that, you are using a 64-bit version of your OS.

I guess that I need to upgrade it to the 64-bit version which is available to download. I'm a bit annoyed that my Pi supplier provided the 32-bit version of the OS rather than the 64-bit one.

**Comment by Webreaper** [comment]
Ah, that's useful to know. Perhaps that's why `app/SolisManager` can't be executed - because it's 32bit.

Unsure if I can built a 32bit version. Probably not. Let me know how it goes with a 64bit OS.

**Comment by Webreaper** [comment]
Just checked, and apparently arm32 is still supported. So I'll see if I can build a 32 bit version later this afternoon.

You might still want to upgrade to 64bit, but it might be a useful test.

**Comment by dqj999** [comment]
If you could build a 32-bit version that would be great. Ideally I'd just stick another SD card in and put a 64-bit version on that, but I'm struggling to find one that will be large enough. I don't want to dump my 32-bit version right now. :-(

**Comment by Webreaper** [comment]
Will have a look at building a 32bit one later.

**Comment by Webreaper** [comment]
I've tried adding linux/arm/6/v5, which might be the 32bit version
(struggling to find clear docs). Have another go at pulling Dev and see if
it's better.

**Comment by Webreaper** [comment]
Oh, and this one should solve that weird Opentelemetry thing.

**Comment by dqj999** [comment]
Thanks for that.

Only just spotted your message.

Ok will try on Monday morning.


Derek

**Comment by dqj999** [comment]
Just tried the latest dev and got this:

docker images
REPOSITORY                    TAG       IMAGE ID       CREATED          SIZE
webreaper/solisagilemanager   dev       71be04e1f4db   26 minutes ago   423MB

docker run -p 5169:5169 71be04e1f4db
exec /app/SolisManager: no such file or directory

I notice that we now have variants v5,v6 and v7 in the manifest file. I think that it might be looking for the V7 one. Has that one been updated?

**Comment by Webreaper** [comment]
Since last night v5, v6 and v7 are all being built. If there's another platform I need to specify for 32-bit RPi, I don't know what it is. But looking....

**Comment by dqj999** [comment]
Yes, I did.

**Comment by Webreaper** [comment]
I'm pretty stumped at the moment then. Will have to ask on StackOverflow. In the meantime, the only short-term option is probably to try the x64 OS on the Pi, but I know that's a bit of a pain for you....

**Comment by Webreaper** [comment]
https://stackoverflow.com/questions/79370927/how-to-build-an-asp-net-core-9-blazor-app-and-dockerise-it-for-a-32-bit-raspberr - let's see.....

**Comment by dqj999** [comment]
I'll switch over to the 64 bit OS, but it's currently on a very slow SD card, at least I hope that is the cause of it running very slowly. Also the 64-bit OS is noticeably less finished off.

I've got a faster card arriving today. All this is a bit mute because I've temporarily switched out of Agile because of the ruinously high rates for today, (up to £1/unit on 20Jan25), but I'll try it now.

**Comment by Webreaper** [comment]
Have you tried putting a non-agile tariff code into the config? In theory it should work with Go or Cosy, but I've never tried.

Rates are a bit painful today...!

**Comment by MartyMoose30053** [comment]
I have managed to sort out my Solis API, I can run the Solisagilemanager from windows no problem.

Now I want to move it to a dedicated Raspberry Pi 4.
I have setup the Raspberry Pi OS, updated.
I have installed Docker(64)
How do I now setup SolisAgileManager to run under docker? also need to have the configurations saved.

Sorry total newbie to all this

**Comment by Webreaper** [comment]
We haven't got it working on RPi yet, so probably best to wait, particularly if you're a docker n00b.

That said, if you want to have a go, look at the readme - there's a docker-compose example on there. As for "how does docker work" - I can't help with that, you'll have to google or post in a docker forum.

**Comment by MartyMoose30053** [comment]
Thank you for all your help in getting this far as a RPi n00b, I'll take your advice and hold off on running it on my RPi and will look at documentation.
I have to say that the App running on windows is a great time saver for me, having manually set them every night for nearly two years!
Some of my observations so far, please do not view this as criticism (I have no room for that as a n00b) 
The charge slot/s are configured in one block overnight, was this for simplicity and reducing the number of writes? When I was configuring this manually I would choose multiple 30min slots where-ever it was cheapest.

Thank you for everyone's kindness and patience

**Comment by dqj999** [comment]
> Now I want to move it to a dedicated Raspberry Pi 4. I have setup the Raspberry Pi OS, updated. I have installed Docker(64) 

I'm trying to install the 64-bit version of Docker on my 64-bit Pi OS but I'm having some issues. I noticed that you had to follow the Debian release instructions, was that you experience as well? Also I got an error installing Docker:

> download.docker.com/linux/debian bookworm InRelease
> 
> ...signatures couldn't be verified because the public key is not available

I'm stuck now but perhaps you can move things forward. 

If you've  got docker installed try doing:

> docker pull webreaper/solisagilemanager:dev

then

> docker images

 to get the downloaded ID

e.g.

> REPOSITORY TAG IMAGE ID CREATED SIZE
> webreaper/solisagilemanager dev _71be04e1f4db_ 26 minutes ago 423MB

then 

docker run -p 5169:5169 _71be04e1f4db_

Good luck!

**Comment by Webreaper** [comment]
Don't use the image ID. It's much easier to just do something like this:

`docker pull webreaper/solisagilemanager:dev`

`docker run -d -name SolisManager -v /some/local/dir:/appdata webreaper/solisagilemanager:dev`

The v argument maps the internal appdata folder to a local folder, which means that your config etc will be saved in there, and next time you pull and run the container, you won't lose all your settings.

**Comment by MartyMoose30053** [comment]
Using the command 

docker run -d -name SolisManager -v /some/local/dir:/appdata webreaper/solisagilemanager:latest

I got the error

unknown shorthand flag: 'n' in -name

**Comment by Webreaper** [comment]
Sorry, it's `--name`. I was typing from memory on a phone....

You'll need to do at least a bit of googling to get through this...

**Comment by Webreaper** [comment]
BTW, please revert to `webreaper/solisagilemanager` (i.e., drop the `dev`) as I released the latest code this morning, and the dev image will likely have breaking changes for the next few days.

**Comment by dqj999** [comment]
Have now got docker running on my 64-bit Pi 3. I'm still getting the same type of error when I try to run the image as before:

sudo docker run  --name SolisManager -v /some/local/dir:/appdata webreaper/solisagilemanager
exec /app/SolisManager: no such file or directory

The architecture is now showing up as aarch64
uname -m
aarch64

which may not be explicitly matched in the manifest

**Comment by Webreaper** [comment]
Can you try running the container interactively?

`docker run -d --entrypoint /bin/bash webreaper/solisagilemanager:dev`

which should get you a bash prompt inside the container. Can you then check if there is a file at `/app/SolisManager`?

If the file is there, can you try `chmod +x /app/SolisManager` and then `/app/SolisManager` to run it?

**Comment by Webreaper** [comment]
According to this page: https://docs.docker.com/build/building/multi-platform/ - `aarch64` should be covered by the `linux/arm64` platform image.

**Comment by Webreaper** [comment]
Just in case it is that `chmod` that's required, I'm pushing a new image to `webreaper/solisagilemanager:dev` with that added to the build.

**Comment by dqj999** [comment]
Sorry still getting the same error:

sudo docker run  --entrypoint /bin/bash webreaper/solisagilemanager:dev
exec /bin/bash: exec format error

sudo docker run -d  --entrypoint /bin/bash webreaper/solisagilemanager:dev
efcb71bf9fa5ec3cc3193405aae45dc4a3c73521c5d4bb4985bf1d9e18d11073

**Comment by Webreaper** [comment]
> sudo docker run --entrypoint /bin/bash webreaper/solisagilemanager:dev exec /bin/bash: exec format error

This implies that even bash in the container isn't the right exe format for the OS. Weird.

> sudo docker run -d --entrypoint /bin/bash webreaper/solisagilemanager:dev
efcb71bf9fa5ec3cc3193405aae45dc4a3c73521c5d4bb4985bf1d9e18d11073

Does this get you a command prompt? If so, can you see if the files exist in `/app`?

**Comment by Webreaper** [comment]
Just for a sanity check, do you want to try this? 

1. Download [SolisManager-raspi.zip](https://github.com/Webreaper/SolisAgileManager/releases/download/1.0.211/SolisManager-raspi.zip) from  https://github.com/Webreaper/SolisAgileManager/releases/tag/1.0.211
2. Copy it onto the pi directly and unzip into a folder
3. You might need to do `chmod +x SolisManager` in the folder you extracted it to
4. Then just run it (`./SolisManager`)

Might be worth seeing if the linux-arm64 version runs outside of docker on the Pi.

**Comment by dqj999** [comment]
Bingo! That's working!! Can I just carry on using that as it stands?

**Comment by Webreaper** [comment]
NIce. 

Yes, you can use that. Docker is easier (except, as we've found out, it isn't). Just means you'll need to unzip/copy the new releases into the same folder in future. It might be possible to automate that with a `curl` + `unzip` script, for ease....

**Comment by Webreaper** [comment]
PS Thanks for the Coffee!

**Comment by Webreaper** [comment]
Going to close this for now - if I get time and somebody with a Pi has the patience we may have another crack at seeing why the ARM64 docker images don't quite work on an arm64 raspberry pi. But installing directly is a decent workaround

**Comment by dqj999** [comment]
I've got a script file to install/update to a Pi from the raspi zip file now so no problems.
I can share if anyone would like it.

**Comment by Webreaper** [comment]
If you can post it here or in a gist that would be great. I could even incorporate it into the bundle.

Thanks!
